import { Sun, Moon, Monitor, Eye } from "lucide-react";
// Theme Configurations - ถนอมสายตา
export const themes = {
  light: {
    name: "Light Mode",
    icon: Sun,
    colors: {
      bg: "bg-gray-50",
      cardBg: "bg-white",
      text: "text-gray-900",
      textSecondary: "text-gray-600",
      border: "border-gray-300",
      accent: "bg-blue-500",
      accentHover: "hover:bg-blue-600",
      button: "bg-purple-600 hover:bg-purple-700",
      textButton: "text-white hover:text-gray-900",
      textSee: "text-gray-900",
      shadow: "shadow-sm",
      textNavbar: "text-gray-900 hover:text-purple-600 transition-colors",
    },
  },
  dark: {
    name: "Dark Mode",
    icon: Moon,
    colors: {
      bg: "bg-gray-900",
      cardBg: "bg-gray-800",
      text: "text-white",
      textSecondary: "text-gray-300",
      border: "border-white",
      accent: "bg-blue-600",
      accentHover: "hover:bg-blue-700",
      button: "bg-gray-800 border-gray-600 hover:!bg-white",
      textButton: "text-white hover:text-gray-900",
      textSee: "text-white hover:text-gray-900",
      shadow: "shadow-lg shadow-black/20",
      textNavbar: "text-white hover:text-purple-600 transition-colors",
    },
  },
  auto: {
    name: "Auto (System)",
    icon: Monitor,
    colors: {
      bg: "bg-gray-50 dark:bg-gray-900",
      cardBg: "bg-white dark:bg-gray-800",
      text: "text-gray-900 dark:text-gray-100",
      textSecondary: "text-gray-600 dark:text-gray-300",
      border: "border-gray-300",
      accent: "bg-blue-500 dark:bg-blue-600",
      accentHover: "hover:bg-blue-600 dark:hover:bg-blue-700",
      button:
        "bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700",
      textButton: "text-white",
      textSee: "text-white hover:text-gray-900",
      shadow: "shadow-sm dark:shadow-lg dark:shadow-black/20",
      textNavbar: "text-white hover:text-purple-600 transition-colors",
    },
  },
  highContrast: {
    name: "High Contrast",
    icon: Eye,
    colors: {
      bg: "bg-yellow-50",
      cardBg: "bg-yellow-50",
      text: "text-gray-900",
      textSecondary: "text-gray-500",
      border: "border-gray-300",
      accent: "bg-yellow-400",
      accentHover: "hover:bg-yellow-300",
      button: "bg-purple-600 hover:bg-purple-700",
      textButton: "text-white",
      textSee: "text-gray-900 hover:text-white",
      shadow: "shadow-xl shadow-gray-500/50",
      textNavbar: "text-gray-900 hover:text-purple-600 transition-colors",
    },
  },
};
